"""
Platform presets define the output specifications for each social media platform.
These map directly to OpenShot Timeline and FFmpegWriter parameters.
"""

PRESETS = {
    "youtube": {
        "label": "YouTube",
        "width": 1920,
        "height": 1080,
        "fps": 30,
        "fps_den": 1,
        "sample_rate": 44100,
        "channels": 2,
        "bitrate": 8_000_000,
        "audio_bitrate": 192_000,
        "codec": "libx264",
        "audio_codec": "aac",
        "max_duration": None,
        "aspect": (16, 9),
        "description": "16:9 HD — standard YouTube upload",
    },
    "tiktok": {
        "label": "TikTok / Reels",
        "width": 1080,
        "height": 1920,
        "fps": 30,
        "fps_den": 1,
        "sample_rate": 44100,
        "channels": 2,
        "bitrate": 6_000_000,
        "audio_bitrate": 128_000,
        "codec": "libx264",
        "audio_codec": "aac",
        "max_duration": 180,
        "aspect": (9, 16),
        "description": "9:16 vertical — TikTok / Instagram Reels / YouTube Shorts",
    },
    "instagram": {
        "label": "Instagram Feed",
        "width": 1080,
        "height": 1080,
        "fps": 30,
        "fps_den": 1,
        "sample_rate": 44100,
        "channels": 2,
        "bitrate": 3_500_000,
        "audio_bitrate": 128_000,
        "codec": "libx264",
        "audio_codec": "aac",
        "max_duration": 60,
        "aspect": (1, 1),
        "description": "1:1 square — Instagram feed post",
    },
    "story": {
        "label": "Instagram / Facebook Story",
        "width": 1080,
        "height": 1920,
        "fps": 30,
        "fps_den": 1,
        "sample_rate": 44100,
        "channels": 2,
        "bitrate": 4_000_000,
        "audio_bitrate": 128_000,
        "codec": "libx264",
        "audio_codec": "aac",
        "max_duration": 15,
        "aspect": (9, 16),
        "description": "9:16 vertical — Instagram/Facebook Story (15 s max)",
    },
    "twitter": {
        "label": "Twitter / X",
        "width": 1280,
        "height": 720,
        "fps": 30,
        "fps_den": 1,
        "sample_rate": 44100,
        "channels": 2,
        "bitrate": 5_000_000,
        "audio_bitrate": 128_000,
        "codec": "libx264",
        "audio_codec": "aac",
        "max_duration": 140,
        "aspect": (16, 9),
        "description": "16:9 720p — Twitter/X (2 m 20 s max)",
    },
    "linkedin": {
        "label": "LinkedIn",
        "width": 1920,
        "height": 1080,
        "fps": 30,
        "fps_den": 1,
        "sample_rate": 44100,
        "channels": 2,
        "bitrate": 5_000_000,
        "audio_bitrate": 128_000,
        "codec": "libx264",
        "audio_codec": "aac",
        "max_duration": 600,
        "aspect": (16, 9),
        "description": "16:9 HD — LinkedIn feed video",
    },
}
